export const SEQUELIZE = 'SEQUELIZE';

export const USER_MODEL = 'USER_MODEL';
export const OTP_CODE_MODEL = 'OTP_CODE_MODEL';
export const STUDENT_MODEL = 'STUDENT_MODEL';
export const STUDENT_PREFERENCE_MODEL = 'STUDENT_PREFERENCE_MODEL';
export const EMPLOYER_MODEL = 'EMPLOYER_MODEL';
export const PLATFORM_SETTING_MODEL = 'PLATFORM_SETTING_MODEL';
export const INTERNSHIP_MODEL = 'INTERNSHIP_MODEL';
export const INTERNSHIP_APPLICATION_MODEL = 'INTERNSHIP_APPLICATION_MODEL';
export const APPLICATION_NOTE_MODEL = 'APPLICATION_NOTE_MODEL';
export const INTERNSHIP_REQUEST_MODEL = 'INTERNSHIP_REQUEST_MODEL';
export const INTEREST_REGISTRATION_MODEL = 'INTEREST_REGISTRATION_MODEL';
